spring:
  application:
    name: core-financas
    
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # MUITO IMPORTANTE: Como já criamos as tabelas no DBeaver, 
      # usamos 'validate' para garantir que o Java não tente recriar ou alterar nada sozinho.
      ddl-auto: validate 
    show-sql: true # Mostra os comandos SQL no terminal (ótimo para estudar)
    properties:
      hibernate:
        format_sql: true
api:
  security:
    token:
      secret: ${API_SECURITY_TOKEN_SECRET}

app:
  timezone: ${APP_TIMEZONE:America/Sao_Paulo}